/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanetFood.Gui;

import PlanetFood.DbUtil.DBConnection;
import PlanetFood.Pojo.UserProfile;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AdminOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionsFrame
     */
    public AdminOptionsFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbUserName.setText("Hello " +UserProfile.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAddProduct = new javax.swing.JRadioButton();
        btnViewProduct = new javax.swing.JRadioButton();
        btnEditProduct = new javax.swing.JRadioButton();
        btnRemoveProduct = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnRegisterCashier = new javax.swing.JRadioButton();
        btnRemoveCashier = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        btnViewOrders = new javax.swing.JRadioButton();
        btnViewDateWise = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        btnAddCategory = new javax.swing.JRadioButton();
        btnEditCategory = new javax.swing.JRadioButton();
        btnViewCategory = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        btnAddEmp = new javax.swing.JRadioButton();
        btnViewEmp = new javax.swing.JRadioButton();
        btnEditEmp = new javax.swing.JRadioButton();
        btnRemoveEmp = new javax.swing.JRadioButton();
        lbUserName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDoTask = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        btnLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THE PLANET FOOD APP\n");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCT OPTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnAddProduct);
        btnAddProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("ADD PRODUCT");
        jPanel2.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 170, -1));

        btnViewProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnViewProduct);
        btnViewProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnViewProduct.setText("VIEW PRODUCT");
        jPanel2.add(btnViewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        btnEditProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnEditProduct);
        btnEditProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEditProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnEditProduct.setText("EDIT PRODUCT");
        jPanel2.add(btnEditProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        btnRemoveProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnRemoveProduct);
        btnRemoveProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRemoveProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveProduct.setText("REMOVE PRODUCT");
        jPanel2.add(btnRemoveProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 190, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 590, 260, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLANET FOOD ADMIN PANEL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MAKE A CHOICE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CASHIER OPTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegisterCashier.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnRegisterCashier);
        btnRegisterCashier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegisterCashier.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterCashier.setText("REGISTER CASHIER");
        btnRegisterCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterCashierActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegisterCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btnRemoveCashier.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnRemoveCashier);
        btnRemoveCashier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRemoveCashier.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveCashier.setText(" REMOVE CASHIER");
        jPanel3.add(btnRemoveCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 280, 250));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPORT OPTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewOrders.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnViewOrders);
        btnViewOrders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnViewOrders.setText("VIEW ORDERS");
        jPanel4.add(btnViewOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btnViewDateWise.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnViewDateWise);
        btnViewDateWise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewDateWise.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDateWise.setText("VIEW DATEWISE");
        jPanel4.add(btnViewDateWise, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 270, 250));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CATEGORY OPTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddCategory.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnAddCategory);
        btnAddCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddCategory.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCategory.setText("ADD CATEGORY");
        jPanel5.add(btnAddCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btnEditCategory.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnEditCategory);
        btnEditCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEditCategory.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCategory.setText("EDIT CATEGORY");
        jPanel5.add(btnEditCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        btnViewCategory.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnViewCategory);
        btnViewCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewCategory.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCategory.setText("VIEW CATEGORY");
        jPanel5.add(btnViewCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 270, 240));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMP OPTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnAddEmp);
        btnAddEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmp.setText("ADD EMP");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });
        jPanel6.add(btnAddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btnViewEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnViewEmp);
        btnViewEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnViewEmp.setText("VIEW EMP");
        jPanel6.add(btnViewEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        btnEditEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnEditEmp);
        btnEditEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEditEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnEditEmp.setText("EDIT EMP");
        jPanel6.add(btnEditEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        btnRemoveEmp.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnRemoveEmp);
        btnRemoveEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRemoveEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveEmp.setText("REMOVE EMP");
        jPanel6.add(btnRemoveEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 270, 250));

        lbUserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 240, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/safe-lock-animation.gif"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, 230));

        btnDoTask.setBackground(new java.awt.Color(0, 102, 102));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 255, 255));
        btnDoTask.setText("DO TASK");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 860, 220, 40));

        btnQuit.setBackground(new java.awt.Color(0, 102, 102));
        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("QUIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 860, 200, 40));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(843, 10, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCashierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterCashierActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddEmpActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure ?","Quitting!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            DBConnection.closeConnection();
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure \n You want to Logout?","Logout",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            this.dispose();
            LoginFrame lf = new LoginFrame();
            lf.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
Frame fr =null;
        if(btnAddEmp.isSelected())
{
      fr = new AddEmpFrame();
  }
else if(btnViewEmp.isSelected())
{
   fr = new ViewEmpFrame();
}
else if(btnEditEmp.isSelected()){
    
    fr= new EditEmpDetailsFrame();
}
else if(btnRemoveEmp.isSelected())
{
    fr = new RemoveEmpFrame();
}
else if(btnRegisterCashier.isSelected()){
    fr = new RegisterCashierFrame();
}
else if(btnRemoveCashier.isSelected()){
    fr = new RemoveCashierFrame();
}
else if(btnViewOrders.isSelected()){
    fr = new AllOrdersDetailsFrame();
}
else if(btnViewDateWise.isSelected()){
    fr = new DateWiseOrdersFrame();
}
else if(btnAddCategory.isSelected()){
    
    fr = new CategoryAddingFrame();
    
}
else if(btnEditCategory.isSelected())
{
   fr = new CategoryEditingFrame(); 
}
else if(btnViewProduct.isSelected()){
  fr = new ViewProductFrame();
    
}
else if(btnEditProduct.isSelected())
{
    fr = new ProductEditingFrame();
}


else{
               JOptionPane.showMessageDialog(null,"Please Select the Option to Perform","No Option Selected!",JOptionPane.ERROR_MESSAGE);
          return ;
       
}  
        if(fr!=null){
fr.setVisible(true);
this.dispose();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
      btnLogout.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
btnLogout.setForeground(Color.white);  // TODO add your handling code here:
   
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAddCategory;
    private javax.swing.JRadioButton btnAddEmp;
    private javax.swing.JRadioButton btnAddProduct;
    private javax.swing.JButton btnDoTask;
    private javax.swing.JRadioButton btnEditCategory;
    private javax.swing.JRadioButton btnEditEmp;
    private javax.swing.JRadioButton btnEditProduct;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton btnQuit;
    private javax.swing.JRadioButton btnRegisterCashier;
    private javax.swing.JRadioButton btnRemoveCashier;
    private javax.swing.JRadioButton btnRemoveEmp;
    private javax.swing.JRadioButton btnRemoveProduct;
    private javax.swing.JRadioButton btnViewCategory;
    private javax.swing.JRadioButton btnViewDateWise;
    private javax.swing.JRadioButton btnViewEmp;
    private javax.swing.JRadioButton btnViewOrders;
    private javax.swing.JRadioButton btnViewProduct;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbUserName;
    // End of variables declaration//GEN-END:variables
}
