/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanetFood.Gui;

import PlanetFood.Dao.CategoryDao;
import PlanetFood.Dao.ProductDao;
import PlanetFood.Pojo.Product;
import PlanetFood.Pojo.UserProfile;
import java.awt.Color;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class SingleProductDetailsFrame extends javax.swing.JFrame {
HashMap<String,String> hm;
HashMap<String,Product> pm ;
 Set al ;
    /**
     * Creates new form SingleProductDetailsFrame
     */
    public SingleProductDetailsFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
         lbUserName.setText("Hello " +UserProfile.getUsername());
 
         try
        {
          hm = CategoryDao.getAllCategoryId();
         Set ks = hm.keySet();
         Iterator it = ks.iterator();
         while(it.hasNext())
         {
             txtcategories.addItem(it.next().toString());
         }
   
        }
        catch(Throwable th)
        {
          th.printStackTrace();
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbUserName = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcategories = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtProdPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtProductId = new javax.swing.JComboBox<>();
        txtProdName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLANET FOOD APP");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SINGLE PRODUCT DETAILS PANEL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 570, 50));

        lbUserName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 30));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHOOSE PRODUCT TO EDIT \n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 26), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 320, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECT PRODUCT ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELECT PRODUCT CATEGORY");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtcategories.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        txtcategories.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtcategoriesItemStateChanged(evt);
            }
        });
        txtcategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtcategoriesMouseExited(evt);
            }
        });
        txtcategories.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtcategoriesCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtcategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcategoriesActionPerformed(evt);
            }
        });
        jPanel3.add(txtcategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 410, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRODUCT PRICE");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        txtProdPrice.setEditable(false);
        txtProdPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtProdPrice.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel3.add(txtProdPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 410, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRODUCT NAME");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        txtProductId.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtProductId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtProductIdItemStateChanged(evt);
            }
        });
        txtProductId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtProductIdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtProductIdMouseExited(evt);
            }
        });
        txtProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIdActionPerformed(evt);
            }
        });
        jPanel3.add(txtProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 410, -1));

        txtProdName.setEditable(false);
        txtProdName.setBackground(new java.awt.Color(255, 255, 255));
        txtProdName.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel3.add(txtProdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 410, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 840, 610));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu card.gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 400, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure \n You want to Logout?","Logout",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            this.dispose();
            LoginFrame lf = new LoginFrame();
            lf.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        btnLogout.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setForeground(Color.white);  // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure ?","Quitting!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            this.dispose();
            ViewProductFrame ad = new ViewProductFrame();
            ad.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtcategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcategoriesActionPerformed
     try
{
  pm  = ProductDao.getAllProductId(hm.get(txtcategories.getSelectedItem().toString()));
  al = pm.keySet();
          Iterator it = al.iterator();
           txtProductId.removeAllItems();
      while(it.hasNext())
              {
                  txtProductId.addItem(it.next().toString());
         }
   
}
catch(Throwable th)
{
    th.printStackTrace();
}
       // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriesActionPerformed

    private void txtcategoriesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtcategoriesItemStateChanged

        
// TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriesItemStateChanged

    private void txtcategoriesCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtcategoriesCaretPositionChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriesCaretPositionChanged

    private void txtcategoriesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcategoriesMouseExited
   

        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriesMouseExited

    private void txtProductIdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProductIdMouseEntered
    // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdMouseEntered

    private void txtProductIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProductIdMouseExited

        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdMouseExited

    private void txtProductIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtProductIdItemStateChanged



        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdItemStateChanged

    private void txtProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIdActionPerformed
     try{
         if(txtProductId.getSelectedItem()==null){
             txtProdName.setText("");
             txtProdPrice.setText("");

             return ;
         }
         
         Product pd = pm.get(txtProductId.getSelectedItem().toString());
    txtProdName.setText(pd.getProdName());
    txtProdPrice.setText(pd.getProdPrice()+"");
}
catch(Throwable th){
    th.printStackTrace();
}   // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingleProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingleProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingleProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingleProductDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingleProductDetailsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtProdPrice;
    private javax.swing.JComboBox<String> txtProductId;
    private javax.swing.JComboBox<String> txtcategories;
    // End of variables declaration//GEN-END:variables
}
