/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanetFood.Gui;

import PlanetFood.Dao.CategoryDao;
import PlanetFood.Dao.OrdersDao;
import PlanetFood.Dao.ProductDao;
import PlanetFood.Pojo.Orders;
import PlanetFood.Pojo.Product;
import PlanetFood.Pojo.UserProfile;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class TakeOrderFrame extends javax.swing.JFrame {
HashMap<String,String> hm;
HashMap<String,Product> pm ;
HashMap<String,list> qm ;
 Set al ;
 int discount;
 String id;
  float gst,Grand_Total ,discPrc;;
 float Sub_Total = 0.0f ;
 
    /**
     * Creates new form TakeOrderFrame
     */
    public TakeOrderFrame() {
        initComponents();
        jPanel1.setFocusable(true);
        this.setLocationRelativeTo(null);
         lbUserName.setText("Hello " +UserProfile.getUsername());
 qm = new HashMap<>();
         try
        {
             id =OrdersDao.getId();
            txtORDId.setText(id);
          hm = CategoryDao.getAllCategoryId();
         Set ks = hm.keySet();
         Iterator it = ks.iterator();
         while(it.hasNext())
         {
             txtcategories.addItem(it.next().toString());
         }
   
        }
        catch(Throwable th)
        {
          th.printStackTrace();
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcategories = new javax.swing.JComboBox<>();
        txtProductId = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        txtProdPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jsProdQty = new javax.swing.JSpinner();
        btnAddOrder = new javax.swing.JButton();
        lbUserName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtOrderList = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtgst = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtORDId = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        txtdiscntP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtGrand = new javax.swing.JTextField();
        btnSaveChanges1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLANET FOOD TAKE ORDER  PANEL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " CHOOSE PRODUCT TO ADD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRODUCT NAME");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRODUCT CATEGORY");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtcategories.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        txtcategories.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtcategoriesItemStateChanged(evt);
            }
        });
        txtcategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtcategoriesMouseExited(evt);
            }
        });
        txtcategories.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtcategoriesCaretPositionChanged(evt);
            }
        });
        txtcategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcategoriesActionPerformed(evt);
            }
        });
        jPanel6.add(txtcategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, -1));

        txtProductId.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtProductId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtProductIdItemStateChanged(evt);
            }
        });
        txtProductId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtProductIdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtProductIdMouseExited(evt);
            }
        });
        txtProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIdActionPerformed(evt);
            }
        });
        jPanel6.add(txtProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 260, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRODUCT ID");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        txtProdName.setEditable(false);
        txtProdName.setBackground(new java.awt.Color(255, 255, 255));
        txtProdName.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel6.add(txtProdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 270, -1));

        txtProdPrice.setEditable(false);
        txtProdPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtProdPrice.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel6.add(txtProdPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 240, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRODUCT PRICE");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRODUCT QUANTITY");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 240, -1));

        jsProdQty.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jsProdQty.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel6.add(jsProdQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 260, -1));

        btnAddOrder.setBackground(new java.awt.Color(0, 102, 102));
        btnAddOrder.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        btnAddOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnAddOrder.setText("ADD ORDER");
        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });
        jPanel6.add(btnAddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 290, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 960, 290));

        lbUserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/safe-lock-animation.gif"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 230));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 0, 100, 40));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALL PRODUCT DETAILS\n\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 26), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtOrderList.setBackground(new java.awt.Color(0, 102, 102));
        jtOrderList.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jtOrderList.setForeground(new java.awt.Color(255, 255, 255));
        jtOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "NAME", "PRICE", "QUANTITY", "AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtOrderList.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jtOrderList);
        if (jtOrderList.getColumnModel().getColumnCount() > 0) {
            jtOrderList.getColumnModel().getColumn(0).setResizable(false);
            jtOrderList.getColumnModel().getColumn(1).setResizable(false);
            jtOrderList.getColumnModel().getColumn(2).setResizable(false);
            jtOrderList.getColumnModel().getColumn(3).setResizable(false);
            jtOrderList.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 950, 480));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 970, 550));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " BASKET INFO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 26), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPay.setBackground(new java.awt.Color(0, 102, 102));
        btnPay.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("PAY BILL");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        jPanel4.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 290, 50));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel4.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 230, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SUB TOTAL");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ORDER ID");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GST AMOUNT");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        txtgst.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel4.add(txtgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 380, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DISCOUNT(");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txtORDId.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel4.add(txtORDId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 380, -1));

        txtSubTotal.setEditable(false);
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel4.add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 380, -1));

        txtdiscntP.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel4.add(txtdiscntP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 380, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GRAND TOTAL");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        txtGrand.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel4.add(txtGrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 380, -1));

        btnSaveChanges1.setBackground(new java.awt.Color(0, 102, 102));
        btnSaveChanges1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        btnSaveChanges1.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveChanges1.setText("PAY BILL");
        btnSaveChanges1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChanges1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSaveChanges1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 290, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 220, 470, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure \n You want to Logout?","Logout",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            this.dispose();
            LoginFrame lf = new LoginFrame();
            lf.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        btnLogout.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setForeground(Color.white);  // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseExited

    private void txtcategoriesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtcategoriesItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriesItemStateChanged

    private void txtcategoriesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcategoriesMouseExited

        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriesMouseExited

    private void txtcategoriesCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtcategoriesCaretPositionChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriesCaretPositionChanged

    private void txtcategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcategoriesActionPerformed
        try
        {
            pm  = ProductDao.getAllProductId(hm.get(txtcategories.getSelectedItem().toString()));
            al = pm.keySet();
            Iterator it = al.iterator();
            txtProductId.removeAllItems();
            while(it.hasNext())
            {
                txtProductId.addItem(it.next().toString());
            }

        }
        catch(Throwable th)
        {
            th.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriesActionPerformed

    private void txtProductIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtProductIdItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdItemStateChanged

    private void txtProductIdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProductIdMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdMouseEntered

    private void txtProductIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProductIdMouseExited

        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdMouseExited

    private void txtProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIdActionPerformed
        try{
            if(txtProductId.getSelectedItem()==null){
                txtProdName.setText("");
                txtProdPrice.setText("");

                return ;
            }

            Product pd = pm.get(txtProductId.getSelectedItem().toString());
            txtProdName.setText(pd.getProdName());
            txtProdPrice.setText(pd.getProdPrice()+"");
        }
        catch(Throwable th){
            th.printStackTrace();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
      try{
          
          
           Orders obj = new Orders();
            obj.setOrd_id(txtORDId.getText());
             obj.setSub_total(Sub_Total);
            obj.setGst(5);
            obj.setGst_amt(gst);
            obj.setGrand_total(Grand_Total);
            obj.setDiscount(discPrc);
            obj.setUser_id(UserProfile.getUsername());
           
            if(OrdersDao.addOrder(obj)){
   JOptionPane.showMessageDialog(null,"Succesfully Order Placed","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
this.dispose();
new TakeOrderFrame().setVisible(true);
            }
      }
      
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"Error occured in db"+ex,"ERROR in DB!",JOptionPane.ERROR_MESSAGE);

            ex.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure ?","Quitting!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            this.dispose();
            AdminOptionsFrame ad = new AdminOptionsFrame();
            ad.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveChanges1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChanges1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveChanges1ActionPerformed

    private void btnAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrderActionPerformed
 DefaultTableModel model = (DefaultTableModel)jtOrderList.getModel();
    jtOrderList.setRowHeight(40);
    float Amount = (Float.parseFloat(txtProdPrice.getText()))*(Integer.parseInt(jsProdQty.getValue().toString()));
    Object[] row = {txtProductId.getSelectedItem(),txtProdName.getText(),txtProdPrice.getText(),jsProdQty.getValue(),Amount};
  list li = new list((int)jsProdQty.getValue(),jtOrderList.getRowCount());
    if(qm.get(txtProductId.getSelectedItem().toString())==null)
   {
    qm.put(txtProductId.getSelectedItem().toString(),li);
   
    model.addRow(row);
   }
   else
   {
    list lo = qm.get(txtProductId.getSelectedItem().toString());
    int ww = (int)jtOrderList.getValueAt(lo.row, 3)+(int)jsProdQty.getValue();
    jtOrderList.setValueAt(ww,lo.row, 3);
    jtOrderList.setValueAt(Amount+(float)jtOrderList.getValueAt(lo.row,4), lo.row, 4);
   }
    Sub_Total = Sub_Total + Amount ;
    txtSubTotal.setText(Sub_Total + "");
   
    discPrc = Math.round(Sub_Total*(discount*0.01f));
   
    txtdiscntP.setText(discPrc+"");
   
    gst = (Sub_Total-discPrc)*(0.05f);
    
    txtgst.setText(gst+"");
    Grand_Total = gst +(Sub_Total-discPrc);
    Grand_Total = Math.round(Grand_Total);
    txtGrand.setText(Grand_Total+"");
    
    





        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddOrderActionPerformed

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
 discount = Integer.parseInt(JOptionPane.showInputDialog(this,"Enter Discount Value","Discount",JOptionPane.INFORMATION_MESSAGE));
            jPanel1.setFocusable(false);
            jLabel11.setText(jLabel11.getText()+discount +"%)");
        

// TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeOrderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnSaveChanges1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jsProdQty;
    private javax.swing.JTable jtOrderList;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JTextField txtGrand;
    private javax.swing.JTextField txtORDId;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtProdPrice;
    private javax.swing.JComboBox<String> txtProductId;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JComboBox<String> txtcategories;
    private javax.swing.JTextField txtdiscntP;
    private javax.swing.JTextField txtgst;
    // End of variables declaration//GEN-END:variables
class list
{
    int qty ;
    int row;

        public list(int qty, int row) {
            this.qty = qty;
            this.row = row;
        }

       
    
}


}
