/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanetFood.Gui;

import PlanetFood.Pojo.UserProfile;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Devendra singh Yadav
 */
public class ViewProductFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionsFrame
     */
    public ViewProductFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
         lbUserName.setText("Hello " +UserProfile.getUsername());
 
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AdminOption = new javax.swing.JPanel();
        AdminPlanetFood = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDoTask = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        btnViewAllProduct = new javax.swing.JRadioButton();
        btnViewSingleProduct = new javax.swing.JRadioButton();
        lbUserName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLANET FOOD APP");
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(102, 102, 102));

        AdminOption.setBackground(new java.awt.Color(0, 102, 102));
        AdminOption.setForeground(new java.awt.Color(0, 102, 102));
        AdminOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminPlanetFood.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        AdminPlanetFood.setForeground(new java.awt.Color(255, 255, 255));
        AdminPlanetFood.setText("VIEW PRODUCTS PANEL");
        AdminOption.add(AdminPlanetFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 48));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Make A choice");
        AdminOption.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 280, -1));

        btnDoTask.setBackground(new java.awt.Color(0, 102, 102));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 255, 255));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });
        AdminOption.add(btnDoTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 590, 260, 50));

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        AdminOption.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, 260, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu card.gif"))); // NOI18N
        AdminOption.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 90, 590, 610));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        AdminOption.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, -1));

        btnViewAllProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnViewAllProduct);
        btnViewAllProduct.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnViewAllProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllProduct.setText("View All Product");
        AdminOption.add(btnViewAllProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 250, -1));

        btnViewSingleProduct.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnViewSingleProduct);
        btnViewSingleProduct.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnViewSingleProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnViewSingleProduct.setText("View Single Product");
        AdminOption.add(btnViewSingleProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 340, -1));

        lbUserName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        AdminOption.add(lbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AdminOption, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
        if(btnViewSingleProduct.isSelected())
        {
          this.dispose();
            SingleProductDetailsFrame sp = new SingleProductDetailsFrame();
             sp.setVisible(true);
            
            
        }
        else if(btnViewAllProduct.isSelected())
        {
           
            AllProductsDetailsFrame vsp=new AllProductsDetailsFrame();
            vsp.setVisible(true);
            this.dispose();
            
        }
        else
        {
            JOptionPane.showConfirmDialog(null,"Make a Choice","Choice!",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AdminOptionsFrame a=new AdminOptionsFrame();
        a.setVisible(true);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure \n You want to Logout?","Logout",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            this.dispose();
            LoginFrame lf = new LoginFrame();
            lf.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        btnLogout.setForeground(Color.yellow);  // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setForeground(Color.white);  // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseExited
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProductFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminOption;
    private javax.swing.JLabel AdminPlanetFood;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDoTask;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JRadioButton btnViewAllProduct;
    private javax.swing.JRadioButton btnViewSingleProduct;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbUserName;
    // End of variables declaration//GEN-END:variables
}
